### ISSUE TITLE
IsCreditCardNumberValid returns incorrect value

### ISSUE THREAD

**Issue by kakarotto67** [yurchik11/Kottans#1]
Pass "35301113333000001" into your IsCreditCardNumberValid method
Expected result: false
Actual result: true (but should be false, as it contains 17 charactersm but JCB accepts only 16 ([check](https://www.wikiwand.com/en/Bank_card_number)))

**Comment by yurchik11** [comment]
here, i also corrected the error and refresh code, as i had written lower, the credit card number will be valid if it has a vendor.  
if ((sum%10 == 0 && sum>0)&&(GetCreditCardVendor(numbers)!="Unknown"))
                return true;
            else
                return false;
