### ISSUE TITLE
Vendor is returned for invalid card number

### ISSUE THREAD

**Issue by kakarotto67** [yurchik11/Kottans#2]
Pass "50000000000006114" into GetCreditCardVendor method
Expected result: Unknown
Actual result: Maestro (just pass this number into your IsCreditCardNumberValid and it will return false, which means that this number isn't valid, so how can it return Maestro?)

**Comment by yurchik11** [comment]
sorry, i corrected the error and refresh code :)

**Comment by kakarotto67** [comment]
Then, please close the issue as described [here](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by yurchik11** [comment]
Fixes #2
