### ISSUE TITLE
GenerateNextCreditCardNumber generates incorrect card number

### ISSUE THREAD

**Issue by kakarotto67** [yurchik11/Kottans#3]
Pass "343434343434343" into GenerateNextCreditCardNumber method
Expected result: "343434343434350"
Actual result: everytime different value (but NEXT valid number should be generated)

**Comment by yurchik11** [comment]
i don`t know how to generate the next credit card number. i saved previous six numbers, which are the code of bank and the code of vendor and next digits generated randomly, which are the code of a bank client and checked full credit number of Luhn algorithm. How should i generate this next credit number?

**Comment by kakarotto67** [comment]
The simplest solution is to increment given value until result is valid according to Luhn algorithm.

**Comment by yurchik11** [comment]
okay, i will do this later. i will send you as soon as possible because i don`t have time right now.

**Comment by yurchik11** [comment]
i had changed the code as you said. Please, check it and send me a reply!
